version: '2'
services:
  customerweb:
    image:
      customerweb-image
    ports:
        - "8085:8085"
    depends_on:
        - customerservice
        - accountservice
  customerservice:
      image:
        customer-service-image
      ports:
        - "8082:8082"
  accountservice:
      image:
        account-service-image
      ports:
        -  "8080:8080"
