version: '2'
services:
  customerweb:
    image:
      customerweb
    ports:
        - "9094:8085"
    depends_on:
        - customerservice
  customerservice:
      image:
        customer-service-image
      ports:
        - "8081:8082"
